ccache
rinatz/playbooks pull request #4
Opened 2022-04-22 14:11 UTC by Raita876

2022-05-07 11:34 UTC, rinatz requested changes

2022-05-07 11:34 UTC, rinatz commented on develop.yml
> +    - ccache
パッケージのインストール順は上に行くほど汎用的なもの、下に行くほど個人的なものというポリシーで並べているため `dotfiles` は一番最後に実行するようにしています。

そのため `ccache` はもう少し上部に書いておきたいです。
プログラミング関係のツールなので `python` の上辺りとかですかね。

2022-05-11 12:41 UTC, Raita876 commented on develop.yml
> +    - ccache
なるほどです。
https://github.com/rinatz/playbooks/pull/4/commits/4d839e6140625368309bf19d1100f8d4117bd73d で修正してみました！

2022-05-13 13:45 UTC, rinatz approved these changes
LGTM

2022-05-13 13:45 UTC, merged