shellcheck を 追加
rinatz/playbooks pull request #6
Opened 2022-09-11 15:29 UTC by Raita876

お久しぶりです :grinning:
playbook に [shellcheck](https://github.com/koalaman/shellcheck) を追加しました。
お時間あるときにレビューいただけると幸いです。

2022-09-12 14:40 UTC, rinatz requested changes

2022-09-12 14:40 UTC, rinatz commented on roles/shellcheck/tasks/AlmaLinux.yml
> +      - Shellcheck
`ShellCheck` じゃないですかね。

2022-09-12 14:40 UTC, rinatz commented on roles/shellcheck/tasks/Amazon.yml
> +      - Shellcheck
ここも `ShellCheck` ですね。

2022-09-12 14:40 UTC, rinatz commented on roles/shellcheck/tasks/CentOS.yml
> +      - Shellcheck
ここも `ShellCheck` ですね。

2022-09-13 11:21 UTC, Raita876 commented on roles/shellcheck/tasks/AlmaLinux.yml
> +      - Shellcheck
失礼しました、タイポですね。 20295a76d7422e92157518f0e0bc01130c1aa845 にて修正しました。

2022-09-13 11:21 UTC, Raita876 commented on roles/shellcheck/tasks/Amazon.yml
> +      - Shellcheck
20295a76d7422e92157518f0e0bc01130c1aa845 にて修正しました。

2022-09-13 11:21 UTC, Raita876 commented on roles/shellcheck/tasks/CentOS.yml
> +      - Shellcheck
20295a76d7422e92157518f0e0bc01130c1aa845 にて修正しました。

2022-09-14 06:03 UTC, rinatz approved these changes

2022-09-14 06:03 UTC, merged

2022-09-14 06:08 UTC, rinatz commented
@Raita876 
ありがとうございます、マージしました！